#!/bin/bash
FUNC="$1";
TYPE="$2";
PARA="$3";

cd ~/Documents/GitHub.nosync/

start(){
    cd ./Ronin/;
    npm run start;
    echo "Running Engine"
};

new(){
    if [ "$1"="svelte" ]; then
         mkdir $2
         cp -a ./svelte-boilerplate/ ./$2/
    echo "Created Project $2";
    fi
};

eval $FUNC $TYPE $PARA;