#! /bin/bash

# SET BASE
SET=0;

# SET CASE
if [[ "$2" = "repo" ]]; then
  SET=1;
fi;

if [[ "$2" = "data" ]]; then
  SET=1;
  cd "./config/";
fi;

# ANNOUNCE FUNC
echo "Git Push at $(pwd)";

# MAKE COMMIT
if [[ "$SET" = 1 ]]; then
git add *;
git commit -m "$3";
git push;
fi;